name: Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: yeslinter

    strategy:
      matrix:
        node-version: ['12.*']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npx eslint .

      - name: Run ESLint
        uses: ./
        with:
          eslint-config-path: '.eslintrc.js'
          eslintignore-path: '.eslintignore'
          repo-token: ${{secrets.GITHUB_TOKEN}}
